services:
  redis:
    image: redis:alpine
    container_name: GrpcClientForTenderService_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=123 # Пароль для Redis
    command: redis-server --requirepass 123 # Исправлено: один $

volumes:
  redis_data: