ENV: "local"
GRPC_REMOTE: "localhost:8081"
HTTP_SERVER:
  SERVER_ADDRESS: "localhost:8082"
  TIMEOUT: 4s
  IDLE_TIMEOUT: 60s
REDIS_SERVER:
  REDIS_ADDRESS: "localhost:6379"
  TIMEOUT: 4s
  REDIS_PASSWORD: "123"
KAFKA:
  KAFKA_ADDRESS: "localhost:29092"
  KAFKA_DEFAULT_TOPIC: "model-events"